name: pr_validation

on:
    pull_request:
        branches: [main]

jobs:
    pr_validation:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - run: npm ci
            - run: npm test
            - run: npm run build
